
###PHPmyAdmin
  - name: install phpmyadmin
    ansible.builtin.apt:
      name: phpmyadmin
      state: latest

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='nicolas' vtype='password'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='nicolas' vtype='password'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='nicolas' vtype='password'

  - name: debconf for pma
    debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

  - name: install pma
    apt: pkg=phpmyadmin state=present

  - name: configure site
    file: path=/var/www/phpmyadmin src=/usr/share/phpmyadmin state=link

  - name: Ensure phpMyAdmin is installed.
    apt:
      name: phpmyadmin
      state: present
    notify: restart apach

  - name: Test if phpmyadmin_database_host is set correctly
    ansible.builtin.assert:
      that:
        - phpmyadmin_database_host is defined
        - phpmyadmin_database_host is string
      quiet: yes

  - name: Ensure phpMyAdmin is installed.
    apt:
      name: phpmyadmin
      state: present
    notify: restart apache

  - name: Ensure phpMyAdmin config file is included in Apache config.
    lineinfile:
      dest: /etc/apache2/apache2.conf
      state: present
      regexp: "^Include.+phpmyadmin.+$"
      line: "Include /etc/phpmyadmin/apache.conf"
      insertafter: "EOF"
      mode: 0644
    notify: restart apache
